### ISSUE TITLE
There was a connection problem to the hosts below. Check ssh host keys.

### ISSUE THREAD

**Issue by adeleglise** [gooddata/serverspec-core#53]
Hi again,

It seems that the serverspec tests cannot connect to distant servers. I've doucle checked that the SSH keys are copied.

Do you have an idea on this issue ?

**Comment by ytsarev** [comment]
Hi, can you provide some output ? in general we are using serverspec both in `:ssh` and `:exec` mode in different scenarios so it should work

**Comment by adeleglise** [comment]
How can I provide you relevant outputs ?

**Comment by ytsarev** [comment]
Just drop the serverspec invocation to gist

**Comment by adeleglise** [comment]
https://gist.github.com/adeleglise/1d9147dba7e078cde28c729f38a6c65c

**Comment by ytsarev** [comment]
0 overall test number? looks like some misconfiguration. Please share the configs if possible

**Comment by adeleglise** [comment]
Rakefile https://gist.github.com/adeleglise/8c1dad81f539a48f8665f7555114b89e
cfg/hosts.yaml https://gist.github.com/adeleglise/5b86276889b990227e6b8cc970887c8e
cfg/serverspec.yml https://gist.github.com/adeleglise/9688171a6d7ff3384e0ce0903c735df5
head of spec/sie/xxxxx_spec.rb https://gist.github.com/adeleglise/165b38fee4eac859f9db13a2bfded71a

**Comment by adeleglise** [comment]
Still no idea on this one ?

**Comment by ytsarev** [comment]
@adeleglise did you declare `SERVERSPEC_ENV` variable ?

**Comment by adeleglise** [comment]
nope

**Comment by ytsarev** [comment]
interesting, it should fail early https://github.com/gooddata/serverspec-core/blob/master/cfg/cfg_helper.rb#L9
Anyway, try `export SERVERSPEC_ENV=awc` and run

**Comment by adeleglise** [comment]
Still nothing :(

**Comment by ytsarev** [comment]
I think i get it.

You've labeled every host in your configuration with
```
  :labels:
    - awc
```
Meanwhile your test spec does not have any label.
I would suggest to remove `awc` label from generic host configuration.
Or label your spec with matching label, e.g.
```
describe command('hostname -f'), label: 'awc' do
  its(:stdout) { should match /xxxxxxxx.xxxxx.xx/}
end
```
But in general labels are supposed to handle special cases without reorganizing test suite, so use them only when you really need it.

**Comment by adeleglise** [comment]
I've removed all the labels, but still 0 overall tests ...

Is there something with the roles too ?

**Comment by ytsarev** [comment]
I see discrepancy of 

```
awc:
  :hosts: hosts.yml
```

vs `cfg/hosts.yaml `

**Comment by adeleglise** [comment]
It's just a typo in the gist file. 

The file is really named "hosts.yml".

**Comment by ytsarev** [comment]
I'm lost then. https://gist.github.com/adeleglise/1d9147dba7e078cde28c729f38a6c65c is it really the whole output ? nothing in stderr ?

**Comment by adeleglise** [comment]
Nothing else. Maybe i should run the task with increased verbosity ? Is there a way to do it ?

**Comment by ytsarev** [comment]
try `format=documentation` from https://github.com/gooddata/serverspec-core#custom-output but it usually increases the verbosity of rspec tests themselves.

**Comment by adeleglise** [comment]
Indeed, no more informations with the format=documentation argument.

I've tried modifiying the suite name, with no effects.

I must admit that i'm kinda stuck.

**Comment by ytsarev** [comment]
@adeleglise can you push you full conf to some repo (obviously with blanking hostnames)? i will try to reproduce the issue.

**Comment by adeleglise** [comment]
Saoory for the delay. I am going to anonymize everything and post the whole repo. 

Anyway, thanks a lot for your help.

**Comment by adeleglise** [comment]
I think we can close this one ^^
